# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

# Testing Lane
# Different parameters can be added from here: https://docs.fastlane.tools/actions/run_tests/#parameters
lane :tests do
  desc "Testing lane"
  # run_tests(workspace: "Example.xcworkspace",
  #          devices: ["iPhone 6s", "iPad Air"],
  #          scheme: "MyAppTests")
            slack_url: "sussex-mcomp.slack.com",
            slack_channel: "#mobile")
end

# To run a test, simply use the terminal command 'fastlane tests' where 'tests' is the name of your lane
