export const FAVOURITE_UNI = 'FAVOURITE_UNI'

export const REQUEST_UNI_LOOKUP_TABLE = 'REQUEST_UNI_LOOKUP_TABLE'
export const RECEIVE_UNI_LOOKUP_TABLE = 'RECEIVE_UNI_LOOKUP_TABLE'
export const UNI_LOOKUP_TABLE_NETWORK_ERR = 'UNI_LOOKUP_TABLE_NETWORK_ERR'
