export const FAVOURITE_UNI = 'FAVOURITE_UNI'

export const REQUEST_UNI_LOOKUP_TABLE = 'REQUEST_UNI_LOOKUP_TABLE'
export const RECEIVE_UNI_LOOKUP_TABLE = 'RECEIVE_UNI_LOOKUP_TABLE'

export const TOGGLE_DEBUG_MODE = 'TOGGLE_DEBUG_MODE'

export const SELECT_TAB = 'SELECT_TAB'
